import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_devtask_agent_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="devtask",
            name="claude_prompt",
            field=models.TextField(
                blank=True,
                help_text="Detailed implementation prompt generated by the Tech Lead agent for Claude Code.",
            ),
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "current_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace",
                        to="team.devtask",
                    ),
                ),
            ],
        ),
    ]
