# Generated by Django 5.0.14 on 2026-03-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_pmconversation_pmmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='devtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('pr_open', 'PR Open'), ('done', 'Done'), ('aborted', 'Aborted')], default='pending', max_length=20),
        ),
    ]
