# Generated by Django 5.0.14 on 2026-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_devtask_created_at_devtask_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtask',
            name='total_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
